### ISSUE TITLE
Error looking for your name

### ISSUE THREAD

**Issue by comste** [p1ngul1n0/blackbird#1]
File "/home/kali/blackbird.py", line 113, in <module>
    asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())
AttributeError: module 'asyncio' has no attribute 'WindowsSelectorEventLoopPolicy'

I get this error !!!!!

**Comment by ajhost** [comment]
Tengo el mismo error. ¿Alguna idea de cómo solucionarlo?.
Gracias.

**Comment by p1ngul1n0** [comment]
Hi!

I just updated the code to fix this issue, please test and report if it's working now.

**Comment by ajhost** [comment]
> Hi!
> 
> I just updated the code to fix this issue, please test and report if it's working now.

Todo perfecto, muchas gracias!
