### ISSUE TITLE
Will there be a webinterface for Blackbird?

### ISSUE THREAD

**Issue by Pitastic** [p1ngul1n0/blackbird#104]
Hey there,

I saw you dropped `flask` 8 month ago. By now I don't see how blackbird could work with a webinterface in the browser (as before).

Are you planning to bring this back again?

As already mentioned the heroku app is not working at the moment, so I guess the answer is _yes_....but how?

**Comment by SpyGamez** [comment]
Is there any update to the WebUI Version? TIA

**Comment by airborne-commando** [comment]
Made a GUI for this.
