### ISSUE TITLE
Feature Request - Hudson Rock Cybercrime Intelligence Integration

### ISSUE THREAD

**Issue by hudsonrock-partnerships** [p1ngul1n0/blackbird#106]
**Suggestion:** 
Consider adding Hudson Rock's complimentary data to receive additional information associated with a username or email address.

**Solution:**
Integrate two complimentary endpoints - 

- Username URL query: https://cavalier.hudsonrock.com/api/json/v2/osint-tools/search-by-username?username=testadmin
- Email URL query: https://cavalier.hudsonrock.com/api/json/v2/osint-tools/search-by-email?email=manvirdi2000@gmail.com

**Good to know:**
We already integrated this data with projects like [IntelOwl](https://github.com/intelowlproject/IntelOwl), [UserFinder](https://github.com/mishakorzik/UserFinder) and [Sherlock](https://github.com/sherlock-project/sherlock).

Thank you!

**Comment by Nthompson096** [comment]
Done this with my own GUI program: https://github.com/Nthompson096/crow

**Comment by Nthompson096** [comment]
Kinda wish I could integrate ot.rocks but that's sadly gone.

**Comment by p1ngul1n0** [comment]
Hi, @hudsonrock-partnerships

Thanks for the suggestion, but this functionality is already integrated with Blackbird.

Blackbird leverages the WhatsMyName project, which includes the Hudson Rock API as part of its supported services. You can find the specific reference in the WhatsMyName data file here: [wmn-data.json#L2546](https://github.com/WebBreacher/WhatsMyName/blob/main/wmn-data.json#L2546).
