### ISSUE TITLE
several queries return false results

### ISSUE THREAD

**Issue by EpicTMC** [p1ngul1n0/blackbird#11]
these all seem to return an account is found however no account exists:
Cash APP account found
Wikipedia account found
Xbox Gamertag account found
Minecraft List account found 
Pinterest account found
Vimeo account found
Telegram account found

**Comment by p1ngul1n0** [comment]
Hi EpicTMC!

I just fixed these false positives, thank you for reporting it.

**Comment by p1ngul1n0** [comment]
Hi EpicTMC!

I just fixed these false positives, thank you for reporting it.
