### ISSUE TITLE
False positives

### ISSUE THREAD

**Issue by kbroughton** [p1ngul1n0/blackbird#12]
The following sites will allways return 200 which shows up as status = "FOUND".
You need more refined tests for them.

"Pinterest"
"Vimeo"
"WordPress Site"
"Universocraft"

**Comment by p1ngul1n0** [comment]
Hi @kbroughton, it's not happing with me, can you please update and check again?

**Comment by kbroughton** [comment]
I searched the name rzlr
It showed "account found" for vimeo and universocraft

https://stats.universocraft.com/stats.php?player=rzlr
https://vimeo.com/rzlr

But visiting the links, both say "not found".

**Comment by p1ngul1n0** [comment]
I tried with the username you gave and resulted in Not Found for both, this could be a Network related problem, what status code these sites gives?
