### ISSUE TITLE
How to enable debug mode?

### ISSUE THREAD

**Issue by shaxiaozz** [p1ngul1n0/blackbird#14]
How to enable debug mode?
![image](https://user-images.githubusercontent.com/43721571/178279304-ff82153b-291c-42cc-9a46-5dbcb2afb01b.png)

And will the http proxy (http://127.0.0.1:8080) be used when the search is initiated?

**Comment by p1ngul1n0** [comment]
Hi!

This output is from the Flask Lib, to enable the debug mode you can modify the code in "webserver.py" and add the param "debug=True" to line 28.

About the HTTP Proxy, currently there isn't a argument to use a Proxy with the search in Blackbird, but it is a planned feature.

**Comment by shaxiaozz** [comment]
> Hi!
> 
> This output is from the Flask Lib, to enable the debug mode you can modify the code in "webserver.py" and add the param "debug=True" to line 28.
> 
> About the HTTP Proxy, currently there isn't a argument to use a Proxy with the search in Blackbird, but it is a planned feature.

**Comment by p1ngul1n0** [comment]
You should add the debug param like this:
```python
app.run('0.0.0.0', debug=True)
```

**Comment by shaxiaozz** [comment]
Thanks, Best Regards
