### ISSUE TITLE
Web server/Permission Denied

### ISSUE THREAD

**Issue by williamfritz** [p1ngul1n0/blackbird#18]
![image](https://user-images.githubusercontent.com/58346524/178860266-52f19be7-fbab-4ccb-aaf8-daabe8d007ec.png)

I get this error when running the program using the web server. It runs great in terminal though! Thank you

**Comment by williamfritz** [comment]
If I try to run it with admin rights I get this 
![image](https://user-images.githubusercontent.com/58346524/178860379-6da46d45-80de-4164-8ce5-e9ce87fc0259.png)

Also I have given the results directory admin rights

**Comment by p1ngul1n0** [comment]
Hi William, i saw that you closed the issue, can you please tell me what was the source of problem?

**Comment by williamfritz** [comment]
Yes. I'm not exactly sure what happened but I was able to get it to bypass
the permission error. It finally let me put sudo in front of the command it
went through without any problems, thankfully. Thank you so much for the
amazing tool!

I did also make a tutorial on using it and put it up on YouTube. Let me
know what you think!

https://youtu.be/phZpEplsn3U
