### ISSUE TITLE
Not responding when running as web server

### ISSUE THREAD

**Issue by shaxiaozz** [p1ngul1n0/blackbird#19]
Hi, here I am again

I'm trying to run blackbird in web mode using the "python blackbird.py --web" directive. The web interface can be opened normally. However, after entering "username" and clicking search, I have been stuck on the "Searching 131 sites for 'username'..." interface and have not returned. As shown below
![image](https://user-images.githubusercontent.com/43721571/178887331-ab20fad3-b6ae-4869-8637-fa5358afba24.png)

I can make sure my network is accessible because I do a command-style search ("python blackbird.py -u just") with success. As shown below
![image](https://user-images.githubusercontent.com/43721571/178888026-206eaa56-78aa-4955-a978-504d096d37eb.png)
![image](https://user-images.githubusercontent.com/43721571/178888128-316852ad-b149-4d06-9198-1464d20fb288.png)

**Comment by shaxiaozz** [comment]
In addition, you can see from F12 that an error occurs when the front-end js code calls the back-end

![image](https://user-images.githubusercontent.com/43721571/178897748-b9fe88cd-e73f-4118-b795-f3f57fc3a105.png)

**Comment by p1ngul1n0** [comment]
Hi shaxiaozz!

Can you show me what error the server response gives please?

Thanks in advance!

**Comment by shaxiaozz** [comment]
Hi p1ngul1n0！Thank you very much for your reply

Check the flask log (debug=true enabled), but no obvious error message is reported.

Look at the source code combined with the F12 console output, it feels like a cross-domain problem, but I see the source code is already cross-domain processing.

I wonder if it's because I run Blackbird with Docker containers.....

Best Regards

**Comment by p1ngul1n0** [comment]
Please verify the HTTP response in network tab in F12.

**Comment by shaxiaozz** [comment]
Please see the screenshot below.
![image](https://user-images.githubusercontent.com/43721571/179649431-7e13d6bb-9c79-4a95-a82a-e7341faa478a.png)

You can visit this address: "http://103.210.21.46:5000/"

**Comment by p1ngul1n0** [comment]
Thanks!

For what i understand, this is happening because the FrontEnd was developed to always fetch localhost, so when you use it in a Docker the FrontEnd can't reach it.

**Comment by shaxiaozz** [comment]
Good.

How can I try to solve it?

**Comment by p1ngul1n0** [comment]
Unfortunately i don't have knowledge on Docker yet, so i can't tell if its possible to fix this error with some Docker container configuration or there is something to be done on FrontEnd.

**Comment by shaxiaozz** [comment]
I tried to change 127.0.0.1:5000 in FrontEnd to the domain name mode. Add host resolution to the container

**Comment by Pitastic** [comment]
> I tried to change 127.0.0.1:5000 in FrontEnd to the domain name mode. Add host resolution to the container

How were you able to change it? And does it help? My Docker is running behind a reverse Proxy on another machine. I request it over a domainname....normally this could be an easy fix...

I found `static/js/Config/api.js`in the browser but I am unable to change original code as everything is minified. I got no experience with react, unfortunately. How can I review/change the FrontEnd code?

**Comment by yllekz** [comment]
I got this same issue. It seems that the container does not work unless you explicitly go to http://127.0.0.1:9797. If you host this container on a network and browse to the page by the host's name, the query never completes.

So there's a workaround but that requires local/direct access to the server that's running the container.

**Comment by Pitastic** [comment]
What workaround could that be?
I think it is as simple as that: JS frontend should query the API on `domain.tld` instead of hardcoded `localhost:port`. But I am unable to fix already minified code...

**Comment by p1ngul1n0** [comment]
Hi!

Thanks for the considerations! So what would be the API domain? We don't have any, we only have the IP from the running machine. If you know about any Docker config that would fix that, please let me know, i didn't found one yet.

Thanks in advance!

**Comment by Pitastic** [comment]
Hi, thanks for answering!

From my understanding this problem cannot be fixed on the server side. So this has nothing to do with any docker settings. 

The browser running the javascript fronted code is aware about the domain/ip of the hosting instance. Here we need to change the fixed `127.0.0.1` to a variable with this value.

Could you share the `js` files in an uncompressed form or give me a hint how to un-minify them? I can see the (false) request to `127.0.0.1` in the browser console but it just lead me to unreadable code...

**Comment by Issomane** [comment]
Hi all, 

I have the same issue while not running in Docker but on an AWS machine. 
Machine is a stock RHEL 7.6 where I have installed blackbird (plus the dependencies obviously). 
I also believe this is due to the localhost IP address being hardcoded somewhere.  

Is there a way to tell the web app to look for resources at another location than 127.0.0.1?
![image](https://user-images.githubusercontent.com/4606467/194503830-f6c5eb1e-fd05-4e3d-a2e5-b8326c21c0cc.png)

Thanks!
Issam

**Comment by Pitastic** [comment]
Hi there !

I just had time to come back to this issue. I really just have a little clue of npm but the fix which was needed is very limited.

I made a [Pull Request](https://github.com/p1ngul1n0/blackbird-react/pull/2) with these changes but was not able to test it with a running backend. However the code compiles in a node.js Docker.

Let me know what you think about it.

Cheers !

**Comment by p1ngul1n0** [comment]
Hi @shaxiaozz !

@Pitastic  did a a awesome contribution with the FrontEnd code that was the root to this problem, can you please try again and see if the error still persists?

Thanks in advance!

**Comment by shaxiaozz** [comment]
@p1ngul1n0 Hi，p1ngul1n0
That's great, this issue has been resolved. As shown below。
![image](https://user-images.githubusercontent.com/43721571/216871906-d8f7cfd4-a64b-4490-b6de-1b77a7306616.png)

Meanwhile, the following is my Dockerfile
```
FROM python:3
ENV PYTHONUNBUFFERED 1
RUN mkdir -p /app/blackbird
ADD . /app/blackbird
WORKDIR /app/blackbird
RUN  apt-get install  default-libmysqlclient-dev -y && \
    ln -sf /usr/share/zoneinfo/Asia/Shanghai  /etc/localtime
RUN pip install --upgrade pip  && \
        pip install -r requirements.txt
ENTRYPOINT ["python","blackbird.py","--web"]
```
