### ISSUE TITLE
Can't run without python3

### ISSUE THREAD

**Issue by domingov89** [p1ngul1n0/blackbird#23]
What can I do if I want to run the tool but I only can do it if I put python3 instead of just put python like the examples? Can someone help me, please?

I usually use Parrot OS.

**Comment by p1ngul1n0** [comment]
Hi Domingov89!

You need to install Python 3 to run Blackbird, otherwhise you will not be able to run it.

**Comment by tjhasan** [comment]
> What can I do if I want to run the tool but I only can do it if I put python3 instead of just put python like the examples? Can someone help me, please?
> 
> I usually use Parrot OS.

So it works if you type `python3` but _not_ if you type `python`? That sounds like an issue with your alias's. 
Go add the following line to your `~/.bashrc` or `~/.bash_aliases` file: `alias python=python3`

Then try it again.
