### ISSUE TITLE
No such file or directory: 'python'

### ISSUE THREAD

**Issue by zombimaster** [p1ngul1n0/blackbird#24]
how to resolve this issue
![image](https://user-images.githubusercontent.com/109542335/179559092-ae543a3c-fdb6-4d65-82af-a44cfeda6bd2.png)

**Comment by mihino89** [comment]
Hi, I had a same problem in clean Ubuntu distribution, the problem is that subprocess can not find python in PATH. My quick fix was to hardcode pathname to python script in "blackbird.py", e.g. see on the snippets. Hope this will resolve your problem. 

Before:
```python
command = subprocess.run(("python", "webserver.py"))
```

After:
```python
command = subprocess.run(("/usr/bin/python3", "webserver.py"))
```

**Comment by p1ngul1n0** [comment]
@Pandede just fixed this issue with the last commit.
