### ISSUE TITLE
Access to 127.0.0.1 was denied

### ISSUE THREAD

**Issue by Drjacky** [p1ngul1n0/blackbird#42]
`python3 blackbird.py --web`:
```bash
  Made with ❤️️ by p1ngul1n0

[!] Started WebServer on http://127.0.0.1:5000/
 * Serving Flask app 'webserver'
 * Debug mode: off
```

http://127.0.0.1:5000/ ->
> Access to 127.0.0.1 was denied
You don't have authorization to view this page.
HTTP ERROR 403

**Comment by p1ngul1n0** [comment]
Hi @Drjacky!

That's looks like a network or file permission related issue, not a problem from the project itself. Please check again, if it persists we can look about it again.
