### ISSUE TITLE
PDF export should be a CLI option

### ISSUE THREAD

**Issue by ghost** [p1ngul1n0/blackbird#44]
I see the web version has this nicely stylised PDF option, and i'd love that as an export option for the CLI, is this something that could be implemented?

Just as an example, export already exists, so could `-ej` (export json) and a new `-ep` (export pdf) option be implemented.

Is this possible?

Thank You

**Comment by p1ngul1n0** [comment]
Hi @SSSEAL-C!

Although it's possible, we would need to search for a good PDF lib for Python.

Currently the PDF is generated by a React LIB, that's the reason that it's only available in the Web Interface.

Thank you!

**Comment by SSSEAL-C** [comment]
I see, is there an online endpoint to retrieve this for a username on the Vercel app?

**Comment by SSSEAL-C** [comment]
Preferably just returning the PDF directly, without all other information.
