### ISSUE TITLE
A better web UI 

### ISSUE THREAD

**Issue by SarkarKurdish** [p1ngul1n0/blackbird#55]
Hey, I noticed the web interface doesn't have a very good UI/UX, do you think a redesign would be a good decision, Also I want to host the website will you choose my Hosting as the official one If i do so? Please note that I'll add google ads in order to make the hosting cost a little cheaper on me

**Comment by p1ngul1n0** [comment]
Hi! The UI was a lot of work to put through and most of the compliments to the tool comes from the UI. If you wish to improve the UI, you can give a look at the FrontEnd of the project https://github.com/p1ngul1n0/blackbird-react.  As of now, i don't have any plans to change the official website to another one.
