### ISSUE TITLE
Webserver no results

### ISSUE THREAD

**Issue by martino1988** [p1ngul1n0/blackbird#6]
Hi, first of all nice work!!! amazing.

my issue is, that the webserver doesnt show any results, just a white screen. the results file (username.json) is fine. kind regards

**Comment by p1ngul1n0** [comment]
Hi Martino!

I just fixed this error, try again and tell me if its working now.

Just a quick explain for why this error was happening:

I added Dribble to the tool yesterday and forgot to add it's logo, so when presenting the results, the frontend couldn't found a Dribbe logo.
