### ISSUE TITLE
Something breaks the program

### ISSUE THREAD

**Issue by Trinadtsatiy** [p1ngul1n0/blackbird#68]
![image](https://github.com/p1ngul1n0/blackbird/assets/108123440/ed7d258b-b7ce-4e69-9c36-239c0bfdbae3)

**Comment by p1ngul1n0** [comment]
Hi @Trinadtsatiy,

Are you trying to run it on Windows? I'm aware of a bug in ASYNCIO that occurs on Windows.

**Comment by Trinadtsatiy** [comment]
> Hi @Trinadtsatiy,
> 
> Are you trying to run it on Windows? I'm aware of a bug in ASYNCIO that occurs on Windows 11

**Comment by Trinadtsatiy** [comment]
> Hi @Trinadtsatiy,
> 
> Are you trying to run it on Windows? I'm aware of a bug in ASYNCIO that occurs on Windows.

Windows 11

**Comment by p1ngul1n0** [comment]
Did this happened in all your executions ?
