### ISSUE TITLE
ModuleNotFound Error

### ISSUE THREAD

**Issue by tlimlam** [p1ngul1n0/blackbird#81]
Hello,

Using the script on Ubuntu VM.

Installation seems to have worked fine. 

But when:

$ python3 blackbird.py --username xxx

I am getting:

Traceback (most recent call last):
  File "/home/ws16/blackbird/blackbird.py", line 11, in <module>
    from modules.whatsmyname.list_operations import checkUpdates
  File "/home/ws16/blackbird/src/modules/whatsmyname/list_operations.py", line 10, in <module>
    from utils.http_client import do_sync_request
ModuleNotFoundError: No module named 'utils.http_client'

Did I do something wrong or does this have to do with the fact WhatsMyName is bugging itself?

Thanks a lot,

**Comment by p1ngul1n0** [comment]
Hi @tlimlam, thats strange.

This seems to be some Ubuntu related error, try to run the script with this command, please:

`sudo python3 blackbird.py --username xxx`

**Comment by tlimlam** [comment]
HI @p1ngul1n0, thanks for the swift response. No luck unfortunately, with the sudo command I am now getting:

Traceback (most recent call last):
  File "/home/ws16/blackbird/blackbird.py", line 3, in <module>
    from rich.console import Console
ModuleNotFoundError: No module named 'rich'

**Comment by tlimlam** [comment]
seems after all that I am missing this module. No clue how to solve it...

ModuleNotFoundError: No module named 'utils.http_client'

**Comment by p1ngul1n0** [comment]
Hi @tlimlam, you just need to run these commands:

sudo pip install -r rewuirements.txt

sudo python blackbird.py --username test

These errors are happening because of your PYTHONPATH, its something that happens on Ubuntu.

**Comment by tlimlam** [comment]
it did work! thank you very much! And the tool works like a charm. Hopefully it won't create too many conflicts if I installed the requirements as sudo...

**Comment by p1ngul1n0** [comment]
That's great! Thanks!
