### ISSUE TITLE
Blackbird web no work

### ISSUE THREAD

**Issue by TrunksDeDBZ** [p1ngul1n0/blackbird#96]
Good morning, 
I can no longer access the site https://blackbird-osint.herokuapp.com/
for a while it has been written "maintenance" can you solve the problem

**Comment by p1ngul1n0** [comment]
Hi @TrunksDeDBZ,

The site is currently offline as I am in the process of developing a new and improved version. This new site will offer enhanced features and greater accuracy. I will publish an update as soon as the new site is available.

Thanks for reaching out.

**Comment by FranzWaismayer** [comment]
An alle
Ich habe blackbird nach Vorgabe installiert.
Bei einer Anfrage bekomme  ich nachfolgende Fehlermeldung: 
![blackbird](https://github.com/p1ngul1n0/blackbird/assets/79380033/d4f711e1-70ff-4d25-895d-4c834327ab37)

**Comment by ZeroFeetAway** [comment]
Die Fehlermeldung, die du erhältst, zeigt an, dass das reportlab-Modul fehlt. reportlab ist eine Python-Bibliothek, die zum Erstellen von PDFs verwendet wird.

Um dies zu beheben, musst du das reportlab-Paket installieren. Du kannst dies mit pip, dem Python-Paketmanager, tun. Hier ist, wie du es installieren kannst:

Öffne ein Terminalfenster.

Führe den folgenden Befehl aus, um reportlab zu installieren:
bash

`pip install reportlab`

Nachdem die Installation abgeschlossen ist, versuche, dein Skript erneut auszuführen.
Das sollte den ModuleNotFoundError beheben und dein Skript sollte ohne Fehler laufen.

**Comment by FranzWaismayer** [comment]
![blackbird_1](https://github.com/user-attachments/assets/202cce75-897f-4712-af1f-745b9a6f3d6a)

Jetzige Fehlermeldung

**Comment by FranzWaismayer** [comment]
![blackbird_1](https://github.com/user-attachments/assets/857afba8-3f62-40b9-b246-d194836368fa)

jetzige Fehlermeldung

**Comment by p1ngul1n0** [comment]
You need to give write and read permission to the logs folder

'chmod a+rw logs'

**Comment by FranzWaismayer** [comment]
![blackbird_2](https://github.com/user-attachments/assets/688fd432-8721-4196-93d4-49d6aa35469d)

jetzt hat wenigstens das programm gestartet und dann das

**Comment by p1ngul1n0** [comment]
The issue arises because Python lacks write permissions for the Blackbird directories. To resolve this, run the following command:

```bash
chmod -R 777 blackbird
```

Additionally, I recommend opening a new issue, as this one is unrelated to your current problem.

**Comment by 47silverfox47** [comment]
New to this, how do I use it?

**Comment by p1ngul1n0** [comment]
Hi,

As dicussed in [Issue#104](https://github.com/p1ngul1n0/blackbird/issues/104#issuecomment-2489053194), Blackbird Web version discontinued due to issues with inaccurate results.
